permissions:
  contents: write 

name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9 # 你项目里实际用的 pnpm 版本

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm build

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: pnpm publish --no-git-checks

      - name: Get version from package.json
        id: get_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Create source archive
        run: |
          tar -czf source-code.tar.gz \
            --exclude='node_modules' \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='*.log' \
            --exclude='.DS_Store' \
            --warning=no-file-changed \
            .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: source-code.tar.gz
          body: |
            ![tinify banner](https://raw.githubusercontent.com/zhuddan/tinify/refs/heads/master/.github/brand.png?raw=true)
            Update to ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
